project_name: ascii-image-converter

before:
  hooks:
    - go mod tidy
    
builds:
  - env:
      - CGO_ENABLED=0
    
    goos:
      - linux
      - windows

    goarch:
      - amd64
      - arm64
      - arm
      - 386

    goarm:
      - 5
      - 6
      - 7
    
archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}_v{{ .Arm }}{{ end }}"
    wrap_in_directory: true

    format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE.txt
    
    replacements:
      linux: Linux
      windows: Windows
      386: 32bit_i386
      amd64: 64bit_amd64
      arm64: 64bit_arm64

checksum:
  name_template: 'sha256_checksums.txt'
  algorithm: sha256
  
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
