project_name: ascii-image-converter

before:
  hooks:
    - go mod tidy
    
builds:
  - env:
      - CGO_ENABLED=0
    
    goos:
      - linux
      - windows

    goarch:
      - amd64
      - arm64
      - arm
      - 386
    
archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true

    format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE.txt
    
    replacements:
      linux: Linux
      windows: Windows
      amd64: amd64_64bit
      arm64: arm64_64bit
      386: i386_32bit
      arm: arm_32bit

checksum:
  name_template: 'sha256_checksums.txt'
  algorithm: sha256
  
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
