project_name: ascii-image-converter

before:
  hooks:
    - go mod tidy
    
builds:
  - env:
      - CGO_ENABLED=0
    
    goos:
      - linux
      - windows
      - darwin

    goarch:
      # Architectures for executable binary generation
      - amd64
      - arm64
      - arm
      - 386

      # # Specifying all architectures for .deb and .rpm generation
      # - 386
      # - amd64
      # - arm
      # - arm64
      # - ppc64
      # - ppc64le
      # - mips
      # - mipsle
      # - mips64
      # - mips64le

    
archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true

    format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE.txt
    
    replacements:
      linux: Linux
      windows: Windows
      darwin: macOS
      amd64: amd64_64bit
      arm64: arm64_64bit
      386: i386_32bit
      arm: arm_32bit

checksum:
  name_template: 'sha256_checksums.txt'
  algorithm: sha256
  
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  -
    package_name: ascii-image-converter
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
      
    homepage: https://github.com/TheZoraiz/ascii-image-converter
    vendor: Zoraiz Hassan
    maintainer: Zoraiz Hassan <hzoraiz8@gmail.com>
    description: Convert images into ascii art
    license: Apache 2.0

    formats:
      - deb
      - rpm
      
    release: 1
    section: graphics
    priority: optional
    bindir: /usr/bin
    
    rpm:
      compression: lzma
