name: ascii-image-converter
base: core18 
version: "1.2.2"
summary: Converts images into ascii format
description: |
  This tool converts images into ascii format and prints them onto the terminal window.
  Supported image formats are JPEG/JPG, PNG, WEBP, BMP and TIFF/TIF. Further configuration can be managed by flags.

grade: stable
confinement: strict

license: Apache-2.0
    
parts:
  ascii-image-converter:
    plugin: go
    go-importpath: github.com/TheZoraiz/ascii-image-converter
    source: .
    build-packages:
      - gcc

apps:
  ascii-image-converter:
    command: bin/ascii-image-converter
    plugs:
    - home
    
architectures:
  - build-on: amd64
    run-on: [arm64, armhf, amd64, i386]
