name: ascii-image-converter
base: core18 
version: "1.5.0"
summary: Convert images and gifs into ascii art
description: |
  This tool converts images and gifs into ascii format and prints them onto the terminal window.
  Supported input formats are JPEG/JPG, PNG, WEBP, BMP TIFF/TIF and GIF. Further configuration can be managed by flags.

grade: stable
confinement: strict

license: Apache-2.0
    
parts:
  ascii-image-converter:
    plugin: go
    go-importpath: github.com/TheZoraiz/ascii-image-converter
    source: .
    build-packages:
      - gcc

apps:
  ascii-image-converter:
    command: bin/ascii-image-converter
    plugs:
    - home
    - network
    
architectures:
  - build-on: amd64
    run-on: [amd64, i386, arm64, armhf, s390x, ppc64el]
